name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.3
  flutter_bloc: ^8.1.6
  very_good_cli: ^0.21.0
  intl: ^0.19.0

  gemini_api:
    path: packages/gemini_api

  storage_api:
    path: packages/storage_api

  cards_api:
    path: packages/cards_api

  cards_repository:
    path: packages/cards_repository
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  main_locale: en_US
  enabled: true